- name: Advanced Service Mesh Course Homework
  hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
  vars:
    api_url: https://api.cluster-5579.5579.sandbox1202.opentlc.com:6443
  tasks:
    - name: Create required bookretail-istio-system namespace
      k8s:
        name: bookretail-istio-system
        kind: Namespace

    - name: Install the Elasticsearch operator
      k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: elasticsearch
            namespace: openshift-operators-redhat
          spec:
            channel: "4.5"
            name: elasticsearch-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Install the Jaeger operator
      k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: jaeger
            namespace: openshift-operators
          spec:
            channel: "stable"
            name: jaeger-product
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Install the Kiali operator
      k8s:
        namespace: bookretail-istio-system
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: kiali
            namespace: openshift-operators
          spec:
            channel: "stable"
            name: kiali-ossm
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Create the Servicemess operator subscription
      k8s:
        definition:
          apiVersion: operators.coreos.com/v1alpha1
          kind: Subscription
          metadata:
            name: servicemesh
            namespace: openshift-operators
          spec:
            channel: stable
            name: servicemeshoperator
            source: redhat-operators
            sourceNamespace: openshift-marketplace

    - name: Create the ServiceMess control plane
      k8s:
        definition:
          apiVersion: maistra.io/v2
          kind: ServiceMeshControlPlane
          metadata:
            name: basic
            namespace: bookretail-istio-system
          spec:
            version: v2.0
            tracing:
              type: Jaeger
              sampling: 10000
            addons:
              jaeger:
                name: jaeger
                install:
                  storage:
                    type: Memory
              kiali:
                enabled: true
                name: kiali
              grafana:
                enabled: true
